name: ğŸ“¦ Release

on:
  push:
    branches:
      - asdasdasd
      
jobs:
  release:
    name: Release
    if: ${{ startsWith( github.event.head_commit.message, 'chore(release)') }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
          
    steps:
      - name: ğŸŸï¸ Checkout Repository
        uses: actions/checkout@v3
          
      - name: âš™ï¸ Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.PAT }}
          release: true
