name: ğŸ“ˆ Bump

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  bump:
    name: Bump
    if: startsWith( github.event.head_commit.message, 'chore(release)' ) != true

    runs-on: ubuntu-latest

    steps:
      - name: ğŸŸï¸ Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          persist-credentials: 'false'

      - name: Conventional Changelog Action
        id: tag_bump
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.PAT }}
          release-count: 0
          skip-ci: false
