name: ğŸ“¦ Release

on:
  push:
    branches:
      - main

jobs:
  preparation:
    name: ğŸ›ï¸ Preparation
    if: ${{ github.event.label.name == 'bump:major' || github.event.label.name == 'bump:minor' || github.event.label.name == 'bump:patch' }}

    runs-on: ubuntu-latest

    outputs:
      id: ${{ steps.release_drafter.outputs.id }}
      tag_name: ${{ steps.release_drafter.outputs.tag_name }}

    steps:
      - name: ğŸŸï¸ Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: ğŸ“ƒ Create Changelog and Release Draft
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ¢ Bump Versions
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording:  'chore(major)'
          minor-wording:  'feat'
          patch-wording:  'fix'

  packaging:
    name: ğŸ“¦ Packaging
    needs: preparation

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: ğŸŸï¸ Checkout Repository
        uses: actions/checkout@v3

      - name: ğŸ§® Setup NodeJS Environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: ğŸ—ƒï¸ Install and Cache Dependencies
        uses: bahmutov/npm-install@v1.8.15
        with:
          install-command: yarn --frozen-lockfile --network-timeout 600000

      - name: ğŸ› ï¸ Build Electron Artifacts
        uses: samuelmeuli/action-electron-builder@v1
        env:
          RESOLVED_VERSION: ${{ needs.preparation.outputs.tag_name }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: false

    #   - name: ğŸ’½ Compact Artifacts
    #     run: tar -cvf electron_build.tar /dist/

      - name: ğŸ“¤ Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron_build_artifact
          path: dist/
          if-no-files-found: error

  release:
    name: ğŸ—ƒï¸ Release Artifacts
    needs: [preparation, packaging]

    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¥ Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: electron_build_artifact
          path: dist/

    #   - name: ğŸ’½ Unzip Artifacts
    #     run: tar -xvf electron_build.tar /dist/

      - name: ğŸ“Œ Attach Artifacts to Release Draft
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "dist/*.exe;dist/*.blockmap"
          overwrite: true
          draft: true
          release_id: ${{ needs.preparation.outputs.id }}
