name: ğŸ“¦ Release

on:
  push:
    branches:
      - main
      
jobs:
  release:
    name: ğŸ› ï¸ Build
    #if: github.event.pull_request.merged == true
    #if: ${{ startsWith(github.ref, 'refs/heads/feature/') || startsWith(github.ref, 'refs/heads/fix/') }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
          
    steps:
      - name: ğŸŸï¸ Checkout Repository
        uses: actions/checkout@v3
        #with:
          #fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
        
      #- name: Get Previous tag
        #id: previoustag
        #uses: WyriHaximus/github-action-get-previous-tag@v1
        #with:
          #fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
          
      - name: ğŸ—ƒï¸ Cache Yarn
        uses: c-hive/gha-yarn-cache@v2
          
      - name: ğŸ§ª Install Dependencies
        run: yarn
          
      - name: Test Build
        run: yarn run build
        
      #- name: Bump release version
        #id: bump_version
        #uses: christian-draeger/increment-semantic-version@1.0.2
        #with:
          #current-version: ${{ steps.previoustag.outputs.tag }}
          #version-fragment: 'feature'
          
      - name: Bump Version and Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.github_token }}
          default_bump: false
          
      - name: New Tag Version
        run: echo ${{ steps.tag_version.outputs.new_tag }}
        
      - name: New Changelog
        run: echo ${{ steps.tag_version.outputs.new_tag }}
        
      - name: âš™ï¸ Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: true
