name: ğŸ“¦ Release

on:
  push:
    branches:
      - main
      
jobs:
  bump:
    name: Bump
    
    outputs:
      new_tag: ${{ steps.tag_bump.outputs.new_tag }}
    
    runs-on: ubuntu-latest
    
    steps:
      - name: ğŸŸï¸ Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
    
      - name: Bump Version and Push Tag
        id: tag_bump
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          DEFAULT_BUMP: none
          WITH_V: true

  release:
    name: Release
    needs: bump

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
          
    steps:
      - name: ğŸŸï¸ Checkout Repository
        uses: actions/checkout@v3
          
      - name: âš™ï¸ Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        if: ${{ needs.bump.outputs.new_tag }}
        with:
          github_token: ${{ secrets.github_token }}
          release: true
