name: ğŸ“¦ Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
	if: ${{ startsWith( github.event.head_commit.message, 'chore(release)' ) }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: ğŸŸï¸ Checkout Repository
        uses: actions/checkout@v3
        #with:
          #fetch-depth: '0'

      #- name: Conventional Changelog Action
        #id: tag_bump
        #uses: TriPSs/conventional-changelog-action@v3
        #with:
          #github-token: ${{ secrets.github_token }}
          #release-count: 0

      - name: âš™ï¸ Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        #if: ${{ steps.tag_bump.outputs.tag }}
        with:
          github_token: ${{ secrets.PAT }}
          release: true
