name: ğŸ“¦ Release

on:
  push:
    branches:
      - main
      
jobs:
  bump:
    name: Release

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
          
    steps:
      - name: ğŸŸï¸ Checkout Repository
        uses: actions/checkout@v3
          
      - name: Bump Version and Push Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.github_token }}
          fetch_all_tags: true
          default_bump: false
        
      - name: Set Initial Tag on Repository
        if: ${{ steps.tag_version.outputs.previous_tag == 'v.0.0.0'}}
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.github_token }}
          custom_tag: 0.0.1
          
      - name: âš™ï¸ Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        if: ${{ steps.tag_version.outputs.new_tag }}
        with:
          github_token: ${{ secrets.github_token }}
          release: true
