name: ğŸ“¦ Release (Deprecated)

on:
  push:
    branches:
      # -  main
      - asasasas

jobs:
  #   setup:
  #     name: Setup Release Draft

  #     runs-on: ubuntu-latest

  #       - name: Generate Changelog
  #         uses: release-drafter/release-drafter@v5
  #         env:
  #           github_token: ${{ secrets.github_token }}
  #         with:
  #           disable-autolabeler: true


  package:
    name: Package

    # Only run if the commit starts with "chore(release)", meaning it comes from the Conventional Changelog Action
    if: startsWith( github.event.head_commit.message, 'chore(release)' )

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: ğŸŸï¸ Checkout Repository
        uses: actions/checkout@v3

      - name: âš™ï¸ Build/Release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        env:
          RESOLVED_VERSION: ${{  }}
        with:
          github_token: ${{ secrets.github_token }}
          release: true
