name: ğŸ“¦ Release

on:
  push:
    branches:
      - main

jobs:
  preparation:
    name: ğŸ›ï¸ Preparation

    runs-on: ubuntu-latest

    outputs:
      id: ${{ steps.release_drafter.outputs.id }}
      tag_name: ${{ steps.release_drafter.outputs.tag_name }}

    steps:
      - name: ğŸŸï¸ Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - name: ğŸ“ƒ Create Changelog and Release Draft
        id: release_drafter
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  packaging:
    name: ğŸ“¦ Packaging
    needs: preparation

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: ğŸŸï¸ Checkout Repository
        uses: actions/checkout@v3

      - name: ğŸ› ï¸ Build Electron Artifacts
        uses: samuelmeuli/action-electron-builder@v1
        env:
          RESOLVED_VERSION: ${{ needs.preparation.outputs.tag_name }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: false

  upload:
    name: ğŸ“¬ Upload Artifacts
    needs: [preparation, packaging]

    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¤ Upload Artifacts to Release Draft
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "dist/*.exe;dist/*.blockmap"
          overwrite: true
          draft: true
          release_id: ${{ needs.preparation.outputs.id }}
